version: '2'

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - /srv/docker/oerctp/postgres_data_dev:/var/lib/postgresql/data
      - /srv/docker/oerctp/postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=oerctp

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=oerctp
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "9112:9112"
    links:
      - postgres
